// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wvcYeuYO-B_12OMfy2UOdSla6gi6Sdo',
    appId: '1:125176977710:web:d97d826d1ae6bfe01602bf',
    messagingSenderId: '125176977710',
    projectId: 'today-do-95b96',
    authDomain: 'today-do-95b96.firebaseapp.com',
    storageBucket: 'today-do-95b96.appspot.com',
    measurementId: 'G-4G5NP202XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsThKHqV-WuHtexAiv6YfKOlRhU4lzY8',
    appId: '1:125176977710:android:2966c51746764e731602bf',
    messagingSenderId: '125176977710',
    projectId: 'today-do-95b96',
    storageBucket: 'today-do-95b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDMNxGbFb4JJZU27MADHKwYNINfcKOro',
    appId: '1:125176977710:ios:e7a63bd2a602d1641602bf',
    messagingSenderId: '125176977710',
    projectId: 'today-do-95b96',
    storageBucket: 'today-do-95b96.appspot.com',
    iosBundleId: 'com.example.toDayDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLDMNxGbFb4JJZU27MADHKwYNINfcKOro',
    appId: '1:125176977710:ios:64afa386c21b9fd51602bf',
    messagingSenderId: '125176977710',
    projectId: 'today-do-95b96',
    storageBucket: 'today-do-95b96.appspot.com',
    iosBundleId: 'com.example.toDayDo.RunnerTests',
  );
}
